### ISSUE TITLE
luci-app-wrtbwmon在lean源码编译没有Luci界面

### ISSUE THREAD

**Issue by firkerword** [haiibo/openwrt-packages#2]
设备是x86  默认lean最新源码编译
编译上之后可以在软件里面看到，但是界面找不到

**Comment by firkerword** [comment]
> lede自带的wrtbwmon要删除掉，这两个插件不一样

是删除了的  要不然冲突编译不了

**Comment by haiibo** [comment]
luci-app-wrtbwmon 和 wrtbwmon 都要添加，我这边编译没问题，你检查检查吧

**Comment by firkerword** [comment]
> luci-app-wrtbwmon 和 wrtbwmon 都要添加，我这边编译没问题，你检查检查吧
谢谢大佬 我没编译nlbw   这个单独编译就无法显示 我弄好了
